### ISSUE TITLE
NullPointerException: Attempt to read from field 'int[] net.ellerton.japng.argb8888.Argb8888Palette.argbArray' on a null object reference

### ISSUE THREAD

**Issue by tateisu** [aellerton/japng#4]
https://mastodon.juggler.jp/system/custom_emojis/images/000/000/422/original/3eb47339da4d1e7a.png

```
D/SubwayTooter: APNGFrames: java.lang.NullPointerException: Attempt to read from field 'int[] net.ellerton.japng.argb8888.Argb8888Palette.argbArray' on a null object reference
D/SubwayTooter: APNGFrames: 	at net.ellerton.japng.argb8888.Argb8888Processors$IndexedColour8.processScanline(Argb8888Processors.java:168)
D/SubwayTooter: APNGFrames: 	at net.ellerton.japng.PngScanlineBuffer.decompress(PngScanlineBuffer.java:112)
D/SubwayTooter: APNGFrames: 	at net.ellerton.japng.argb8888.Argb8888Processor.processFrameImageData(Argb8888Processor.java:151)
D/SubwayTooter: APNGFrames: 	at net.ellerton.japng.reader.DefaultPngChunkReader.readImageDataChunk(DefaultPngChunkReader.java:175)
D/SubwayTooter: APNGFrames: 	at net.ellerton.japng.reader.DefaultPngChunkReader.readChunk(DefaultPngChunkReader.java:66)
D/SubwayTooter: APNGFrames: 	at net.ellerton.japng.reader.PngReadHelper.read(PngReadHelper.java:63)
D/SubwayTooter: APNGFrames: 	at jp.juggler.subwaytooter.util.APNGFrames.parseAPNG(APNGFrames.java:458)
D/SubwayTooter: APNGFrames: 	at jp.juggler.subwaytooter.util.CustomEmojiCache$Worker.decodeAPNG(CustomEmojiCache.java:244)
D/SubwayTooter: APNGFrames: 	at jp.juggler.subwaytooter.util.CustomEmojiCache$Worker.run(CustomEmojiCache.java:156)
D/SubwayTooter: CustomEmojiCache: PNG decode failed. https://mastodon.juggler.jp/system/custom_emojis/images/000/000/422/original/3eb47339da4d1e7a.png?1506079832 
```

**Comment by xiazdong** [comment]
if the image bitdepth is 8, i also have the problem. it the image bitdepth is 32, it is ok.

**Comment by xiazdong** [comment]
[japng.jar.zip](https://github.com/aellerton/japng/files/1356384/japng.jar.zip)

use this jar

**Comment by aellerton** [comment]
Thanks for these reports and sorry I've been slow to respond. Release deadlines! @xiazdong what is the code difference in your zip? Can you post or reference to an image that crashes so I can add it to the test list? (or just test it internally but not add it to the test list).
Thanks!
